FROM debian:bookworm-slim
RUN apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends \
    iptables iproute2 procps curl iputils-ping python3 netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*
