[mypy]
python_version = 3.12
warn_return_any = false
warn_unused_ignores = true
ignore_missing_imports = true
check_untyped_defs = false
disallow_untyped_defs = false
disallow_incomplete_defs = false

[mypy-tests.*]
ignore_errors = true
